---
- name: Install specified packages
  hosts: remote
  become: true
  tasks:
    - name: Ensure required packages are installed
      package:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ packages }}"
