---
- name: Install specified packages
  hosts: remote
  become: true
  tasks:
    - name: Install curl
      package:
        name: curl
        state: present
      when: "'curl' in packages"

    - name: Install htop
      package:
        name: htop
        state: present
      when: "'htop' in packages"