---
- name: Ensure required packages are installed
  hosts: remote
  become: true
  tasks:
    - name: Remove conflicting packages
      package:
        name: curl-minimal
        state: absent

    - name: Install wget
      package:
        name: wget
        state: present
      when: "'wget' in packages"

    - name: Install procps-ng (provides top)
      package:
        name: procps-ng
        state: present
      when: "'top' in packages"
